### ISSUE TITLE
Issue with multiple process only CPU!!

### ISSUE THREAD

**Issue by aj280192** [ShawXh/DeepWalk-dgl#1]
I am facing an issue when trying to run multiple processes with only the CPU setup. But there is no issue when running with single process. It is an Assertion Error: "Torch not compiled with CUDA enabled". Is there a way to run multiple processes with the only CPU. Below is the error detail. 

Unhandled exception in thread started by <function thread_wrapped_func.<locals>.decorated_function.<locals>._queue_result at 0x0000027DB407C048>
Traceback (most recent call last):
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 30, in _queue_result
    res = func(*args, **kwargs)
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 125, in fast_train_sp
    trainer.emb_model.set_device(gpu_id)
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\model.py", line 146, in set_device
    self.lookup_table = self.lookup_table.to(self.device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 149, in _lazy_init
    _check_driver()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 33, in _queue_result
    trace = traceback.format_exc()
NameError: name 'traceback' is not defined
Using backend: pytorch
num batchs: 5 in subprocess [1]
The device is cuda:1
Unhandled exception in thread started by <function thread_wrapped_func.<locals>.decorated_function.<locals>._queue_result at 0x000002151C2AC048>
Traceback (most recent call last):
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 30, in _queue_result
    res = func(*args, **kwargs)
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 125, in fast_train_sp
    trainer.emb_model.set_device(gpu_id)
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\model.py", line 146, in set_device
    self.lookup_table = self.lookup_table.to(self.device)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 149, in _lazy_init
    _check_driver()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ajay madhavan\Documents\GE project\DeepWalk-dgl-master\DeepWalk-dgl-master\deepwalk-final.py", line 33, in _queue_result
    trace = traceback.format_exc()
NameError: name 'traceback' is not defined

**Comment by ShawXh** [comment]
Hi there, thanks for your issues. Actually this is a test ropo. The full version is here https://github.com/dmlc/dgl/tree/master/examples/pytorch/deepwalk

**Comment by aj280192** [comment]
Thank you ShawXh I will refer to the full version!!
